### PR TITLE
Auto update

### PR DESCRIPTION
**Pull request by tsebens**
Script to automatically update the data files from their respective directories

### CODE REVIEW

**Comment by mikelehen** [comment]
Can you also add requirements.txt and any other boostrapping stuff people will need to run this?  Maybe  borrow from SETUP.md in the covid-data-model repo?

**Comment by jredding** [comment]
I'm going to be the cranky old man here - but I'm a little curious if we are overcomplicating this. 

For timeseries we can do just 
data = panda.open_csv(<url>) 

or in a script we can do 
curl -o <url>   

I'm just curious why we are building a class, a python script, etc. for something pretty straightforward in a script.. 

even the JHU data is 
curl <url> |unzip  

not trying to be a jerk - but I do worry about over abstraction/complication.

**Comment by mikelehen** [comment]
FWIW- I initially was just leaning towards simple shell scripts.  But folks on Slack indicated a preference for python and I was won over when I realized that for the JHU data I really would like to capture the git sha that we're downloading.  And the method I came up with to do that is to grab https://api.github.com/repos/CSSEGISandData/COVID-19/branches/master and parse the JSON...  which isn't something I really want to do in bash.

**Comment by tsebens** [comment]
If I'm being honest, over-engineering is something I'm prone to, so it's totally possible that this is over developed for its purposes. 

I will say that pd.read_csv isn't an option for the JHU data, because it's locked in a git repo so we have to pull the whole thing down first.

I'll separate the scripts and add the version files. Forgot about that part.

**Comment by jredding** [comment]
That is helpful I appreciate the background - I can't be in all conversations. I just have a genuine concern for over abstraction and increasingly the complexity.  

Our goal is to make it easier to iterate on new models, explore new methods, and introduce new data. The more difficult that becomes the less new scientists will want to come in and explore the models.

**Comment by mikelehen** [comment]
@jredding Yeah, totally agree. Though I honestly don't know what data scientist / modeling people are most comfortable with and if bash or python is better. 🤷‍♂

**Comment by tsebens** [comment]
Moved the script in the `scripts` directory. It's still a single file but now you can pass flag arguments to it to specify which dataset you want to update
```
python scripts/update.py -cds # Downloads the Corona Data Scraper data

python scripts/update.py -jhu # Downloads the John Hopkins University data

python scripts/update.py -cds -jhu # Download both CDS and JHU

python scripts/update.py # Download from all data sources
```

Updates track date, time, and commit hash (for JHU) in version.txt. Tracked separately for each source

**Comment by jredding** [comment]
Ok. I'm won over with this approach. It's pretty clean when it's separated in the files.

**Comment by mikelehen** [comment]
Sorry, but what's the motivation for putting everything into a single script like this?

I think we may end up with dozens of datasets that we deal with (different sources for case data, sources for hospital beds, sources for interventions, sources for measured effects of social distancing like transit data, etc.), and I don't know that we want to cram all of that into a single script.  It'll make it more likely people step on each other's toes (merge conflicts).  

Also we may have some datasets with updaters that aren't written in python (e.g. the [existing AEI scraper](https://github.com/covid-projections/covid-projections/blob/develop/scripts/interventions-data.js) I wrote is written in JavaScript but could be rewritten in python if we were so inclined).

So I would prefer splitting this into two scripts like I suggested originally.  And then we can have a single update-all.py or update-all.sh that runs them

Or do you think the code duplication ends up being too much or something?

**Comment by mikelehen** [comment]
Merged, though I may still split this into two scripts.

**Pull request merged**
